name: sitkpy

channels:
  - conda-forge
  
dependencies:
  - python=3.13
  - pip
  - pip:
    - notebook~=7.0
    - matplotlib
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - multiprocess
    - SimpleITK>=2.2.0
    - ipympl

    
