name: sitkpy

channels:
  - conda-forge
  
dependencies:
  - pip
  - pip:
    - python=3.13
    - jupyter~=7.0
    - matplotlib
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - multiprocess
    - SimpleITK>=2.2.0
    - ipympl

    
